### ISSUE TITLE
Support for dbtunnel proxy

### ISSUE THREAD

**Issue by stikkireddy** [stikkireddy/dbtunnel#7]
* chainlit (partially implemented without share)
* dash
* fastapi
* flask
* nicegui
* shiny-python
* solara

**Comment by yrwrstnhtmr** [comment]
"chainlit (partially implemented without share)" - does this mean I can't share the link even if someone has attach permission on my cluster? Because that seems to be the case for me.

**Comment by stikkireddy** [comment]
@yrwrstnhtmr all the work is done i will close this issue. you can share via the link. You can share links, this was a past limitation that i was able to get around with a custom proxy.
